import type { ContractDiffReport } from '../report/ContractDiffReport.js'
import type { DiffChange } from '../models/types.js'

const MARKER = '<!-- api-contract-diff-report -->'

const RISK_EMOJI: Record<string, string> = {
  NONE:     '✅',
  LOW:      '🔵',
  MEDIUM:   '🟡',
  HIGH:     '🔴',
  CRITICAL: '🚨',
}

/**
 * Generates a Markdown PR comment body from a ContractDiffReport.
 *
 * The comment includes a hidden marker so the GitHub Action can find and
 * update it on subsequent pushes instead of posting duplicate comments.
 */
export function generatePRComment(report: ContractDiffReport): string {
  const { metadata, summary, riskLevel, riskScore, changes, impacts } = report
  const emoji = RISK_EMOJI[riskLevel] ?? '⚠️'
  const breaking = changes.filter(c => c.breaking)
  const nonBreaking = changes.filter(c => !c.breaking)
  const breakingImpacts = impacts.filter(r => r.change.breaking)

  const lines: string[] = [
    MARKER,
    '',
    `## ${emoji} API Contract Diff — ${riskLevel} Risk`,
    '',
    `**${metadata.oldTitle}** \`v${metadata.oldVersion}\` → \`v${metadata.newVersion}\``,
    '',
    '| Metric | Value |',
    '|--------|-------|',
    `| Total changes | **${summary.total}** |`,
    `| Breaking | **${summary.breaking}** |`,
    `| Non-breaking | **${summary.nonBreaking}** |`,
    `| Risk score | **${riskScore}** (${riskLevel}) |`,
    `| HIGH / MEDIUM / LOW | ${summary.bySeverity.HIGH} / ${summary.bySeverity.MEDIUM} / ${summary.bySeverity.LOW} |`,
    '',
  ]

  if (breaking.length > 0) {
    lines.push('<details>')
    lines.push(`<summary>🔴 <strong>Breaking Changes (${breaking.length})</strong></summary>`)
    lines.push('')
    lines.push('| Severity | Method | Path | Description |')
    lines.push('|----------|--------|------|-------------|')
    for (const c of breaking) {
      lines.push(changeRow(c))
    }
    lines.push('')
    lines.push('</details>')
    lines.push('')
  }

  if (nonBreaking.length > 0) {
    lines.push('<details>')
    lines.push(`<summary>✅ <strong>Non-Breaking Changes (${nonBreaking.length})</strong></summary>`)
    lines.push('')
    lines.push('| Severity | Method | Path | Description |')
    lines.push('|----------|--------|------|-------------|')
    for (const c of nonBreaking) {
      lines.push(changeRow(c))
    }
    lines.push('')
    lines.push('</details>')
    lines.push('')
  }

  if (breakingImpacts.length > 0) {
    lines.push('<details>')
    lines.push(`<summary>⚠️ <strong>Consumer Impact Analysis (${breakingImpacts.length} affected)</strong></summary>`)
    lines.push('')
    for (const r of breakingImpacts) {
      const { change, impacts: impactLines } = r
      const method = change.method ? `\`${change.method.toUpperCase()}\` ` : ''
      lines.push(`**${change.severity}** ${method}\`${change.path}\` — ${change.description}`)
      for (const impact of impactLines) {
        lines.push(`- ${impact}`)
      }
      lines.push('')
    }
    lines.push('</details>')
    lines.push('')
  }

  if (summary.total === 0) {
    lines.push('> ✅ **No changes detected** — the contracts are identical.')
    lines.push('')
  }

  lines.push('---')
  lines.push(`*Generated by [api-contract-diff](https://github.com/your-org/api-contract-diff) v${report.toolVersion} at ${report.generatedAt.slice(0, 19).replace('T', ' ')} UTC*`)

  return lines.join('\n')
}

function changeRow(c: DiffChange): string {
  const method = c.method ? `\`${c.method.toUpperCase()}\`` : '—'
  return `| ${c.severity} | ${method} | \`${c.path}\` | ${c.description} |`
}

/**
 * Returns the hidden marker string used to identify existing bot comments.
 * GitHub Action uses this to find and update the comment in place.
 */
export function getPRCommentMarker(): string {
  return MARKER
}
